DROP TABLE IF EXISTS TBL_USER;
 
CREATE TABLE TBL_USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  status VARCHAR(250) DEFAULT NULL
);